// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSnTJVyowfpip5iulsU_4MBj3cEkl2qk',
    appId: '1:723696301841:web:b8339c408af5a176043eb0',
    messagingSenderId: '723696301841',
    projectId: 'recipe--app-130e3',
    authDomain: 'recipe--app-130e3.firebaseapp.com',
    storageBucket: 'recipe--app-130e3.firebasestorage.app',
    measurementId: 'G-NMV0KT3RN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVJftRYe9hk940KMj8eQM3lYdoZ-t6Mk',
    appId: '1:723696301841:android:b63229573011a492043eb0',
    messagingSenderId: '723696301841',
    projectId: 'recipe--app-130e3',
    storageBucket: 'recipe--app-130e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHYLtOAgXIbvK0ZDVqKnR72kTr-JQjVw',
    appId: '1:723696301841:ios:7842a9295c0f3f13043eb0',
    messagingSenderId: '723696301841',
    projectId: 'recipe--app-130e3',
    storageBucket: 'recipe--app-130e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZHYLtOAgXIbvK0ZDVqKnR72kTr-JQjVw',
    appId: '1:723696301841:ios:7842a9295c0f3f13043eb0',
    messagingSenderId: '723696301841',
    projectId: 'recipe--app-130e3',
    storageBucket: 'recipe--app-130e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeSnTJVyowfpip5iulsU_4MBj3cEkl2qk',
    appId: '1:723696301841:web:ebf310f67c522a8d043eb0',
    messagingSenderId: '723696301841',
    projectId: 'recipe--app-130e3',
    authDomain: 'recipe--app-130e3.firebaseapp.com',
    storageBucket: 'recipe--app-130e3.firebasestorage.app',
    measurementId: 'G-8T6P6SS326',
  );
}
